### ISSUE TITLE
Support for openai streaming responses in genai scenarios

### ISSUE THREAD

**Issue by kshitijcode** [Azure/apim-landing-zone-accelerator#128]
Currently we get an internal server error 

`Expression evaluation failed. The message body is not a valid JSON. Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue
`

on streaming use cases in https://github.com/Azure/apim-landing-zone-accelerator/blob/main/scenarios/workload-genai/policies/genai-policy.xml

` <choose>
            <when condition="@(context.Response.StatusCode == 200)">
                
                
                <set-body>@{                   
                JObject api_response = context.Response.Body.As&lt;JObject&gt;(preserveContent: true);                
                return api_response.ToString();                         
                }</set-body>
            </when>`
            
  We need to put a condition that this only applies for non streaming scenarios.

**Comment by prasann** [comment]
discussed with @kshitijcode , not picking up this issue for now.
