### ISSUE TITLE
Parametrize backend bicep and ensure consistent passing with main.bicep

### ISSUE THREAD

**Issue by cykreng** [Azure/apim-landing-zone-accelerator#18]
From Enterprise-Scale-APIM created by [cykreng](https://github.com/cykreng): cykreng/Enterprise-Scale-APIM#28  

null

**Comment by cykreng** [comment]
added workload and environment parameters accordingly naming convention and created pull request

**Comment by cykreng** [comment]
Cynthia, can you please set it to resolved after my PR got approved and applied? Thx

**Comment by cykreng** [comment]
please check what parameters are missing in the current version

**Comment by cykreng** [comment]
Should be fixed with PR #47

**Comment by briggsb9** [comment]
Updated as part of refactoring.
