### ISSUE TITLE
Update the reference links in user-guide to reflect the new /reference-implementations/ folder

### ISSUE THREAD

**Issue by cykreng** [Azure/apim-landing-zone-accelerator#2]
From Enterprise-Scale-APIM created by [paromitaroy](https://github.com/paromitaroy): cykreng/Enterprise-Scale-APIM#72  

Since the deployment folder has been removed and the files have been moved under /reference-implementations/ folder, update the ref . links in the user guide.

**Comment by cykreng** [comment]
PR raised

**Comment by briggsb9** [comment]
Documentation re-done as part of refactoring.
