### ISSUE TITLE
Terraform implementation

### ISSUE THREAD

**Issue by cykreng** [Azure/apim-landing-zone-accelerator#5]
From Enterprise-Scale-APIM created by [cykreng](https://github.com/cykreng): cykreng/Enterprise-Scale-APIM#63  

null

**Comment by cykreng** [comment]
Created a branch and added the folder structure (which might need some re-tweaking when we start writing the tf files. 

Have booked a meeting 27/01 with Pete to dicuss the ref implementation.

**Comment by paromitaroy** [comment]
PR has been raised, need a review @cykreng @petemessina

**Comment by briggsb9** [comment]
Stale and no longer relevant due to refactoring. Terraform planned.
