### ISSUE TITLE
create vmwindows fails as a result of refactoring

### ISSUE THREAD

**Issue by cykreng** [Azure/apim-landing-zone-accelerator#7]
From Enterprise-Scale-APIM created by [ahmedsza](https://github.com/ahmedsza): cykreng/Enterprise-Scale-APIM#56  

@briandenicola 
in createvmwindows this was modified to
module nic './vm-nic.bicep' = {
  name: '${vmName}-nic'
  params: {
    location: location
    subnetId: subnetId
    nicName: '${vmName}-nic'
  }
}

but there is no nicName parameter in vm-nic.bicep. Either need to revert to vmname or variable name in vmnic needs to be changed

**Comment by briggsb9** [comment]
Stale and no longer relevant due to refactoring.
