### ISSUE TITLE
Enable APIM managed identity for named values stored in Key Vault

### ISSUE THREAD

**Issue by briggsb9** [Azure/apim-landing-zone-accelerator#75]
When creating APIM policies customers often like to reference secrets stored in Key Vault for use in APIM named values. Seeing as though storing secrets in Key Vault is deemed best practice, we should enable a managed identity on APIM and assign get and list permissions to the shared services Key Vault.

[Reference](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-properties?tabs=azure-portal)

> Using key vault secrets is recommended because it helps improve API Management security:
> 
> Secrets stored in key vaults can be reused across services
> Granular [access policies](https://learn.microsoft.com/en-us/azure/key-vault/general/security-features#privileged-access) can be applied to secrets
> Secrets updated in the key vault are automatically rotated in API Management. After update in the key vault, a named value in API Management is updated within 4 hours. You can also manually refresh the secret using the Azure portal or via the management REST API.

Happy to work on this if agreed.

**Comment by aionic** [comment]
Hey @briggsb9, I'm not sure if you're still up for working on your enhancement but we would welcome a pull request if you are.
